apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker-node
  name: worker-node
spec:
  selector:
    app: worker-node
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
